{% set data = load_setup_py_data() %}

package:
  name: "asali"
  version: {{ data.get('version') }}

source:
  path: .

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"

requirements:
  build:
    - pip
    - python {{ python }}
  host:
    - python {{ python }}
    - assimulo
    - pint
    - cantera
    - termcolor
    - matplotlib
    - pyyaml
  run:
    - python {{ python }}
    - assimulo
    - pint
    - cantera
    - termcolor
    - matplotlib
    - pyyaml

test:
  imports:
    - asali

  source_files:
    - tests
    - run_tests.py

  commands:
    - python run_tests.py

about:
  home: https://srebughini.github.io/ASALI/
  summary: "A Python package to simulate chemical reactors"
  license: GPL
  license_family: GPL
  license_file: LICENSE
  dev_url: https://github.com/srebughini/ASALIPY
  description: A Python package to simulate chemical reactors
  doc_url: https://srebughini.github.io/ASALI/docs/api-python/

extra:
  recipe-maintainers:
    - srebughini