{% set data = load_setup_py_data() %}

package:
  name: "asali"
  version: {{ data.get('version') }}

source:
  path: .

build:
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"

requirements:
  build:
    - pip
    - python {{ python }}
  host:
    - python {{ python }}
    - assimulo
    - pint
    - cantera
    - termcolor
    - matplotlib
  run:
    - python {{ python }}
    - assimulo
    - pint
    - cantera
    - termcolor
    - matplotlib

test:
  imports:
    - asali

  source_files:
    - tests
    - run_tests.py

  commands:
    - python run_tests.py

about:
  home: https://github.com/srebughini/ASALIPY
  license: GPL
  summary: Library to model chemical reactors
  license_file: LICENSE

extra:
  recipe-maintainers:
    - srebughini