package:
  name: "asali"
  version: "0.1"

source:
  path: ../.

build:
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"

requirements:
  build:
    - pip
    - python
  host:
    - python
    - assimulo
    - pint
    - cantera
    - termcolor
    - matplotlib
  run:
    - python
    - assimulo
    - pint
    - cantera
    - termcolor
    - matplotlib

test:
  imports:
    - asali

  source_files:
    - tests
    - run_tests.py

  commands:
    - python run_tests.py

about:
  home: https://github.com/srebughini/ASALIPY
  license: GPL
  license_file: LICENSE
  summary: Library to model chemical reactors