{% set data = load_setup_py_data() %}

package:
  name: "asali"
  version: {{ data.get('version') }}

source:
  path: ../.

build:
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"

requirements:
  build:
    - pip
    - python
  host:
    - python
    - assimulo
    - pint
    - cantera
    - termcolor
    - matplotlib
  run:
    - python
    - assimulo
    - pint
    - cantera
    - termcolor
    - matplotlib

test:
  imports:
    - asali

  source_files:
    - tests
    - run_tests.py

  commands:
    - python run_tests.py

about:
  home: {{ data.get('home-page') }}
  license: {{ data.get('license') }}
  license_file: {{ data.get('license-file') }}
  summary: {{ data.get('description') }}